services:

  redis-weather-cache:
    image: redis:7.4.2
    ports:
    - 6379:6379

  current-weather-app:
    image: cw-api:1.0.0
    restart: on-failure
    environment:
      - ASPNETCORE_URLS=http://+:5074 
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING:-redis://redis-weather-cache:6379}
    ports:
      - 8888:5074