services:

  # TODO - Move to using secrets from github in production!
  # NOTE - Look into docker swarm?
  redis-weather-cache:
    build:
      context: ./CurrentWeatherApp
      dockerfile: Dockerfile.Redis
    volumes:
      - ./CurrentWeatherApp/redis/redis-conf:/usr/local/etc/redis/redis-conf
      - ./CurrentWeatherApp/redis/redis-certs:/usr/local/etc/redis/certs
    # TODO set in production file env_file: .env.cw
    ports:
    - 6379:6379  
    command: >
      sh -c "ls -la /usr/local/etc/redis/certs/ &&
             envsubst < /usr/local/etc/redis/redis-conf/redis.conf.template > /usr/local/etc/redis/redis-conf/redis.conf &&
             cat /usr/local/etc/redis/redis-conf/redis.conf &&
             redis-server /usr/local/etc/redis/redis-conf/redis.conf"

  current-weather-app:
    restart: on-failure
    volumes:
     - ./CurrentWeatherApp/redis/redis-client:/etc/redis/certs
     - ./CurrentWeatherApp/CurrentWeatherAPI:/src/CurrentWeatherAPI
    # TODO set in production file env_file: .env.redis-cw
    depends_on:
      - redis-weather-cache
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5074
    ports:
      - 8888:5074