services:

  redis-weather-cache:
    build:
      context: ./CurrentWeatherApp
      dockerfile: Dockerfile.Redis
    ports:
    - 6379:6379  
    command: >
      sh -c "ls -la /usr/local/etc/redis/certs/ &&
             envsubst < /usr/local/etc/redis/redis-conf/redis.conf.template > /usr/local/etc/redis/redis-conf/redis.conf &&
             cat /usr/local/etc/redis/redis-conf/redis.conf &&
             redis-server /usr/local/etc/redis/redis-conf/redis.conf"

  current-weather-app:
    restart: on-failure
    build:
      context: ./CurrentWeatherApp
      dockerfile: Dockerfile.production
    depends_on:
      - redis-weather-cache
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5074
    ports:
      - 8888:5074
  
  warning-fetcher-app:
    restart: on-failure
    # TODO add prod build context
    ports:
      - 8000:8000
  
  # TODO - add WarningFetcherApp here