# Dockercompose.development
services:

  redis-weather-cache:
    volumes:
        - ./CurrentWeatherApp/redis/redis-conf:/usr/local/etc/redis/redis-conf
        - ./CurrentWeatherApp/redis/redis-certs:/usr/local/etc/redis/certs
    environment:
      - REDIS_TLS_CERT_FILE=/usr/local/etc/redis/certs/redis_server.crt
      - REDIS_TLS_KEY_FILE=/usr/local/etc/redis/certs/redis_server.key
      - REDIS_TLS_CA_CERT_FILE=/usr/local/etc/redis/certs/ca_client.crt
    # TODO - Can this be used in production too?

  current-weather-app:
    build:
      context: ./CurrentWeatherApp
      dockerfile: Dockerfile.development
    
    volumes:
     - ./CurrentWeatherApp/redis/redis-client:/etc/redis/certs
     - ./CurrentWeatherApp/CurrentWeatherAPI:/src/CurrentWeatherAPI
     - /src/CurrentWeatherAPI/bin/
     - /src/CurrentWeatherAPI/obj/
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1