# Dockercompose.development
services:

  redis-weather-cache:
    volumes:
      - ./CurrentWeatherApp/redis/redis-conf:/usr/local/etc/redis/redis-conf
      - ./CurrentWeatherApp/redis/redis-certs:/usr/local/etc/redis/certs
    env_file: ./dev-env/.env.redis-cw
    
  current-weather-app:
    image: cw-api:1.0.0
    build:
      context: ./CurrentWeatherApp
      dockerfile: Dockerfile.development
    volumes:
     - ./CurrentWeatherApp/redis/redis-client:/etc/redis/certs
     - ./CurrentWeatherApp/CurrentWeatherAPI:/src/CurrentWeatherAPI
     - /src/CurrentWeatherAPI/bin/
     - /src/CurrentWeatherAPI/obj/
    env_file: ./dev-env/.env.cw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
    
  warning-fetcher-app:
    build:
      context: ./WarningFetcherApp
      dockerfile: Dockerfile.development
    env_file: ./dev-env/.env.wf