apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: weather-app
build:
  artifacts:
    - image: current-weather-app
      docker:
        dockerfile: Dockerfile
      context: ./CurrentWeatherApp
manifests:
  rawYaml:
    - ./CurrentWeatherApp/k8s/CurrentWeather.yaml
deploy:
  kubectl: {}
# Setup profiles here