FROM python:3.12-slim
WORKDIR usr/src
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# TODO - add ports and stuff?
CMD ["fastapi", "dev", "--host", "0.0.0.0", "./app/main.py"]