
FROM python:3.9
WORKDIR usr/src
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . ./app
# TODO https://fastapi.tiangolo.com/deployment/docker/#behind-a-tls-termination-proxy if running behind TLS
CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]