
FROM python:3.12-slim
WORKDIR usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
# TODO https://fastapi.tiangolo.com/deployment/docker/#behind-a-tls-termination-proxy if running behind TLS
CMD ["fastapi", "run", "./main.py", "--host", "0.0.0.0", "--port", "8000"]