name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          export GITHUB_REPOSITORY=$GITHUB_REPOSITORY_LOWERCASE
          docker compose -f docker-compose.yaml -f docker-compose.production.yaml build
          docker compose -f docker-compose.yaml -f docker-compose.production.yaml push