name: Deploy Weather App

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  CERT_PATH: CurrentWeatherApp/redis/redis-certs
  CLIENT_PATH: CurrentWeatherApp/redis/redis-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create cert directories
        run: |
          mkdir -p $CERT_PATH
          mkdir -p $CLIENT_PATH
        
      - name: Create cert files
        run: |
         echo "${{ secrets._REDIS_CLIENT_PFX }}" | base64 -d >  ${CLIENT_PATH}/client.pfx
         echo "${{ secrets._REDIS_SERVER_PEM }}" | base64 -d > ${CLIENT_PATH}/ca_server.pem
         echo "${{ secrets._REDIS_TLS_CERT }}" | base64 -d > ${CERT_PATH}/redis_server.crt
         echo "${{ secrets._REDIS_TLS_KEY }}" | base64 -d > ${CERT_PATH}/redis_server.key
         echo "${{ secrets._REDIS_TLS_CA_CERT }}" | base64 -d > ${CERT_PATH}/ca.crt
         chmod 600 ${CERT_PATH}/*
         chmod 600 ${CLIENT_PATH}/*

         if ! echo "${{ secrets._REDIS_CLIENT_PFX }}" | base64 -d >  ${CLIENT_PATH}/client.pfx; then
            echo "Failed to create client.pfx"
            exit 1
          fi

         if ! [ -f "${CLIENT_PATH}/client.pfx" ] || ! [ -f "${CERT_PATH}/redis_server.crt" ]; then
            echo "Certificate files are missing"
            exit 1
          fi

      - name: Create .env file
        run: printenv | grep '^REDIS_\|^CW_' > .env
        env: ${{ toJSON(secrets) }}
      
      # TODO - setup deploy step here to digital ocean?
