name: Deploy Weather App

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  CERT_PATH: /opt/weather-app/certs
  CLIENT_PATH: /opt/weather-app/client-certs
  DOCKER_CONFIG_PATH: /opt/weather-app/docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: ${{ secrets.DO_KNOWN_HOSTS }}

      - name: Setup remote directories
        run: |
          ssh root@${{ secrets.DO_HOST }} "mkdir -p ${CERT_PATH} ${CLIENT_PATH} ${DOCKER_CONFIG_PATH}"

      - name: Copy certificates
        run: |
          echo "${{ secrets._REDIS_CLIENT_PFX }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CLIENT_PATH}/client.pfx"
          echo "${{ secrets._REDIS_SERVER_PEM }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CLIENT_PATH}/ca_server.pem"
          echo "${{ secrets._REDIS_TLS_CERT }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/redis_server.crt"
          echo "${{ secrets._REDIS_TLS_KEY }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/redis_server.key"
          echo "${{ secrets._REDIS_TLS_CA_CERT }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/ca.crt"
      
      # TODO - get redis.conf onto the server
      

      - name: Set permissions
        run: |
          ssh root@${{ secrets.DO_HOST }} "chmod 600 ${CERT_PATH}/* ${CLIENT_PATH}/*"

      - name: Copy docker files
        run: |
          scp docker-compose.yaml docker-compose.production.yaml root@${{ secrets.DO_HOST }}:${DOCKER_CONFIG_PATH}/
          printenv | grep '^REDIS_\|^CW_' | ssh root@${{ secrets.DO_HOST }} "cat > ${DOCKER_CONFIG_PATH}/.env"
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          CW_REDIS_CONNECTION_STRING: ${{ secrets.CW_REDIS_CONNECTION_STRING }}
          CW_REDIS_PFX_PW: ${{ secrets.CW_REDIS_PFX_PW }}
          # TODO - Move to using proper variables for paths here and in docker-compose
          CW_REDIS_SERVER_PEM_PATH: /etc/redis/certs/ca_server.pem
          CW_REDIS_PFX_PATH: /etc/redis/certs/client.pfx
          REDIS_TLS_CERT_FILE: /usr/local/etc/redis/certs/redis_server.crt
          REDIS_TLS_KEY_FILE: /usr/local/etc/redis/certs/redis_server.key
          REDIS_TLS_CA_CERT_FILE: /usr/local/etc/redis/certs/ca.crt


          # TODO add paths to the files

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.GITHUB_TOKEN }} | ssh root@${{ secrets.DO_HOST }} "docker login ghcr.io -u ${{ github.actor }} --password-stdin"
          ssh root@${{ secrets.DO_HOST }} "export GITHUB_REPOSITORY=$GITHUB_REPOSITORY_LOWERCASE && cd ${DOCKER_CONFIG_PATH} && docker compose pull && docker compose -f docker-compose.yaml -f docker-compose.production.yaml up -d"

