name: Deploy Weather App

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  CERT_PATH: /opt/weather-app/certs
  CLIENT_PATH: /opt/weather-app/client-certs
  DOCKER_CONFIG_PATH: /opt/weather-app/docker
  REDIS_CONFIG_PATH: /opt/weather-app/redis-conf
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4 

      # TODO - split these into 2 or 3 jobs?

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          export GITHUB_REPOSITORY=$GITHUB_REPOSITORY_LOWERCASE
          docker compose -f docker-compose.yaml -f docker-compose.production.yaml build
          docker compose -f docker-compose.yaml -f docker-compose.production.yaml push
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: ${{ secrets.DO_KNOWN_HOSTS }}

      - name: Setup remote directories
        run: |
          ssh root@${{ secrets.DO_HOST }} "mkdir -p ${CERT_PATH} ${CLIENT_PATH} ${DOCKER_CONFIG_PATH} ${REDIS_CONFIG_PATH}"

      - name: Copy certificates
        run: |
          echo "${{ secrets._REDIS_CLIENT_PFX }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CLIENT_PATH}/client.pfx"
          echo "${{ secrets._REDIS_SERVER_PEM }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CLIENT_PATH}/ca_server.pem"
          echo "${{ secrets._REDIS_TLS_CERT }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/redis_server.crt"
          echo "${{ secrets._REDIS_TLS_KEY }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/redis_server.key"
          echo "${{ secrets._REDIS_TLS_CA_CERT }}" | base64 -d | ssh root@${{ secrets.DO_HOST }} "cat > ${CERT_PATH}/ca.crt"      

      - name: Set permissions
        run: |
          ssh root@${{ secrets.DO_HOST }} "chmod 600 ${CERT_PATH}/* ${CLIENT_PATH}/*"

      - name: Copy docker files
        run: |
          scp ./CurrentWeatherApp/redis/redis-conf/redis.conf.template root@${{ secrets.DO_HOST }}:${REDIS_CONFIG_PATH}/
          scp docker-compose.yaml docker-compose.production.yaml root@${{ secrets.DO_HOST }}:${DOCKER_CONFIG_PATH}/

      # TODO - this wont scale at all so we should try and move to docker swarm at some point...
      - name: Deploy
        run: |
          GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.GITHUB_TOKEN }} | ssh root@${{ secrets.DO_HOST }} "docker login ghcr.io -u ${{ github.actor }} --password-stdin"
          ssh root@${{ secrets.DO_HOST }} "cd ${DOCKER_CONFIG_PATH} && \
            docker compose pull && \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY_LOWERCASE \
            REDIS_PASSWORD='${{ secrets.REDIS_PASSWORD }}' \
            REDIS_USERNAME='${{ secrets.REDIS_USERNAME }}' \
            CW_REDIS_CONNECTION_STRING='${{ secrets.CW_REDIS_CONNECTION_STRING }}' \
            CW_REDIS_PFX_PW='${{ secrets.CW_REDIS_PFX_PW }}' \
            CW_REDIS_SERVER_PEM_PATH=/etc/redis/certs/ca_server.pem \
            CW_REDIS_PFX_PATH=/etc/redis/certs/client.pfx \
            REDIS_TLS_CERT_FILE=/usr/local/etc/redis/certs/redis_server.crt \
            REDIS_TLS_KEY_FILE=/usr/local/etc/redis/certs/redis_server.key \
            REDIS_TLS_CA_CERT_FILE=/usr/local/etc/redis/certs/ca.crt \
            docker compose -f docker-compose.yaml -f docker-compose.production.yaml up -d"