name: Pytest

on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    - "wf/**"
    - "warning-fetcher/**"
    paths:
    - "WarningFetcherApp/**"
  pull_request:
    branches:
      - "main"
      - "wf/**"
      - "WarningFetcherApp/**"
    paths:
    - "WarningFetcherApp/**"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './WarningFetcherApp'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.12.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test with pytest 
      run: pytest --tb=line --no-header -vv -r -W ignore::DeprecationWarning
